# Gait Def for crawl (匍匐前进)

# 1 - FR摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 1, 1]
duration = 10

[[section]]
contact  = [0, 1, 1, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 2 - RL摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 1, 0]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 3 - FL摆动，其他三腿支撑
[[section]]
contact  = [1, 0, 1, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 4 - RR摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 0, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 重复循环
# 5 - FR摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 1, 1]
duration = 10

[[section]]
contact  = [0, 1, 1, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 6 - RL摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 1, 0]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 7 - FL摆动，其他三腿支撑
[[section]]
contact  = [1, 0, 1, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 8 - RR摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 0, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5 

# 重复循环
# 5 - FR摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 1, 1]
duration = 10

[[section]]
contact  = [0, 1, 1, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 6 - RL摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 1, 0]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 7 - FL摆动，其他三腿支撑
[[section]]
contact  = [1, 0, 1, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5

# 8 - RR摆动，其他三腿支撑
[[section]]
contact  = [1, 1, 0, 1]
duration = 15

[[section]]
contact  = [1, 1, 1, 1]
duration = 5 