# Gait Params for crawl
[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.0, 0.0, 0.8,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 300

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.0, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 20030.0, 20020.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.0, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 20020.0, 30020.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.09, 0.0, 0.0, 0.0,]
step_height = [ 30020.0, 20020.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.09, 0.0, 0.0, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.09, 0.0, 0.09, 0.0,]
step_height = [ 20020.0, 20030.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.09, 0.0, 0.09, 0.0, 0.09, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.09, 0.0, 0.09, 0.0,]
step_height = [ 20030.0, 20020.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.09, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.09, 0.0, 0.09, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.16, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.09, 0.0, 0.09, 0.0,]
step_height = [ 20020.0, 30020.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.16, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.09, 0.0, 0.09, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.16, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.16, 0.0, 0.09, 0.0,]
step_height = [ 30020.0, 20020.0,]
value = 0
duration = 450

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.16, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.16, 0.0, 0.09, 0.0,]
step_height = [ 20020.0, 20020.0,]
value = 0
duration = 150

[[step]]
mode = 11
gait_id = 110
contact = 20
life_count = 0
vel_des = [ 0.1, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, -0.17,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 50.0,]
ctrl_point = [ 0.16, 0.0, 0.8,]
foot_pose = [ 0.16, 0.0, 0.16, 0.0, 0.16, 0.0,]
step_height = [ 20020.0, 20030.0,]
value = 0
duration = 450

